name: PS2 ELF Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build PS2 Project
        run: |
          shell: bash
          run: |
            source $PS2DEV/ps2sdk/bin/ps2sdk-setup.sh || true
            make
            
